# -*- coding: utf-8 -*-
"""FormativeAssessment1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dLnD-gHncFK_ZCyozmi1GHjFQNF-1RUg
"""

print('Using functions ord, chr, & bin')

#this function is used to display the numerical value of an alphabet
print(ord('Q'))
print('this number is the numerical value of the letter Q')

#this function displays the alphabet of the entered numerical value
print(chr(76))
print('76 represents L')

#this function displays the binary form.
print(bin(97))
print('this is the binary form of the letter a')